worlds:
  base: world
health:
  min-hearts: 8
  max-hearts: 20
hunger:
  effective-min: 20
  effective-max: 80
sleep-vote:
  enabled: true
build:
  enabled: true
death-chest:
  enabled: true
  burn-minutes: 30
